yarnPath: .yarn/releases/yarn-3.6.0.cjs
packageExtensions:
  "@parcel/workers@2.8.3":
    dependencies:
      "@parcel/core": "2.8.3"
  "@parcel/fs@2.8.3":
    dependencies:
      "@parcel/core": "2.8.3"
  "@parcel/cache@2.8.3":
    dependencies:
      "@parcel/core": "2.8.3"
  "@parcel/package-manager@2.8.3":
    dependencies:
      "@parcel/core": "2.8.3"
  "@parcel/babel-plugin-transform-runtime@2.8.3":
    dependencies:
      "@parcel/core": "2.8.3"
      "@babel/core": "7.22.1"
  "@parcel/transformer-babel@2.8.3":
    dependencies:
      "@babel/plugin-transform-runtime": "7.22.4"
      "@babel/core": "7.22.1"
